# Custom gitleaks config to ignore false positives in src/backend/auth.py
# The entire file is allowlisted to avoid secret scanning false positives in password logic.

[allowlist]
  description = "Ignore all findings in src/backend/auth.py"
  paths = ["src/backend/auth.py"]

# Inherit all default rules
[extend]
  config = "default"
