version: '3.8'

services:
  chatbot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "7860:7860"
    environment:
      - PYTHONUNBUFFERED=1
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - IN_DOCKER=1
      - PRODUCTION=true
      - DOCKER_MODE=prod
      - TZ=Asia/Singapore
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - chatbot-network

  benchmark:
    build:
      context: .
      dockerfile: docker/Dockerfile.benchmark
    environment:
      - PYTHONUNBUFFERED=1
      - BENCHMARK_MODE=true
      - TZ=Asia/Singapore
    volumes:
      - ./data:/app/data
      - ./benchmark_results:/app/results
      - ./.env:/app/.env:ro
      - ~/Downloads:/app/host_downloads
    profiles:
      - benchmark
    networks:
      - chatbot-network

  docs:
    build:
      context: .
      dockerfile: docker/Dockerfile.docs
    ports:
      - "8000:8000"
    volumes:
      - ./docs:/app/docs
      - ./docs/_build:/app/docs/_build
    environment:
      - PYTHONUNBUFFERED=1
    profiles:
      - docs
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge

volumes:
  chatbot-data:
    driver: local
